spring.application.name=Tienda de ropa de daniel

# Hibernate crea la tabla automáticamente
spring.jpa.hibernate.ddl-auto=create

# Evitar que Spring ejecute data.sql automáticamente
spring.sql.init.mode=never

# Habilitar consola H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Mostrar SQL en consola (opcional)
spring.jpa.show-sql=true
